"""
Cocotb Test Generator.

Generates cocotb tests from MicroArchSpec and TimingScenario.
"""

from typing import List, Dict, Any, Optional
from pathlib import Path
import json


class CocotbTestGenerator:
    """
    Cocotb test generator.

    Generates cocotb Python test files from architecture specs and timing scenarios.
    """

    def __init__(self, output_dir: Path = Path(".")):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_module_test(self, module_spec: Dict[str, Any],
                            clock_period_ns: float = 6.4) -> str:
        """
        Generate a basic cocotb test framework for a single module.

        Args:
            module_spec: Module specification dictionary
            clock_period_ns: Clock period in nanoseconds

        Returns:
            Generated Python test code
        """
        module_name = module_spec['name']
        ports = module_spec.get('ports', [])

        # Find clock and reset signals
        clk_port = next((p for p in ports if p.get('protocol') == 'clock'), None)
        rst_port = next((p for p in ports if p.get('protocol') == 'reset'), None)

        clk_name = clk_port['name'] if clk_port else 'clk'
        rst_name = rst_port['name'] if rst_port else 'rst_n'
        rst_active_low = '_n' in rst_name

        test_code = f'''"""
Cocotb testbench for {module_name}
Auto-generated by VeriFlow Stage 2
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge, Timer
from cocotb.types import LogicArray
import random


async def reset_dut(dut, duration_ns={clock_period_ns * 5}):
    """Apply reset to the DUT"""
    dut.{rst_name}.value = {"0" if rst_active_low else "1"}
    await Timer(duration_ns, units="ns")
    dut.{rst_name}.value = {"1" if rst_active_low else "0"}
    await Timer(duration_ns, units="ns")


@cocotb.test()
async def test_{module_name}_basic(dut):
    """Basic functionality test for {module_name}"""

    # Start clock
    clock = Clock(dut.{clk_name}, {clock_period_ns}, units="ns")
    cocotb.start_soon(clock.start())

    # Reset
    await reset_dut(dut)

    # Wait a few cycles
    for _ in range(10):
        await RisingEdge(dut.{clk_name})

    dut._log.info("Basic test completed")


@cocotb.test()
async def test_{module_name}_random(dut):
    """Random stimulus test for {module_name}"""

    # Start clock
    clock = Clock(dut.{clk_name}, {clock_period_ns}, units="ns")
    cocotb.start_soon(clock.start())

    # Reset
    await reset_dut(dut)

    # Apply random stimulus
    for i in range(100):
'''

        # Generate random stimulus for input ports
        input_ports = [p for p in ports if p['direction'] == 'input'
                      and p.get('protocol') not in ['clock', 'reset']]

        for port in input_ports:
            width = port['width']
            port_name = port['name']
            if width == 1:
                test_code += f"        dut.{port_name}.value = random.randint(0, 1)\n"
            else:
                test_code += f"        dut.{port_name}.value = random.randint(0, 2**{width}-1)\n"

        test_code += f'''
        await RisingEdge(dut.{clk_name})

    dut._log.info("Random test completed")
'''

        return test_code

    def generate_axi_stream_test(self, module_spec: Dict[str, Any],
                                 test_data: List[int],
                                 clock_period_ns: float = 6.4) -> str:
        """
        Generate test for AXI-Stream interface modules.

        Args:
            module_spec: Module specification
            test_data: List of test data values
            clock_period_ns: Clock period in nanoseconds

        Returns:
            Generated test code
        """
        module_name = module_spec['name']
        ports = module_spec.get('ports', [])

        # Find AXI-Stream ports
        axi_ports = [p for p in ports if p.get('protocol') == 'axi_stream']

        clk_port = next((p for p in ports if p.get('protocol') == 'clock'), None)
        rst_port = next((p for p in ports if p.get('protocol') == 'reset'), None)

        clk_name = clk_port['name'] if clk_port else 'clk'
        rst_name = rst_port['name'] if rst_port else 'rst_n'
        rst_active_low = '_n' in rst_name

        test_code = f'''"""
AXI-Stream testbench for {module_name}
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, FallingEdge
from cocotb.types import LogicArray


async def axi_stream_write(dut, data_list, tdata_signal, tvalid_signal,
                          tready_signal, tlast_signal=None):
    """Write data via AXI-Stream interface"""
    for i, data in enumerate(data_list):
        tdata_signal.value = data
        tvalid_signal.value = 1
        if tlast_signal and i == len(data_list) - 1:
            tlast_signal.value = 1
        else:
            if tlast_signal:
                tlast_signal.value = 0

        await RisingEdge(dut.{clk_name})
        while tready_signal.value == 0:
            await RisingEdge(dut.{clk_name})

    tvalid_signal.value = 0
    if tlast_signal:
        tlast_signal.value = 0


async def axi_stream_read(dut, count, tdata_signal, tvalid_signal,
                         tready_signal, tlast_signal=None):
    """Read data via AXI-Stream interface"""
    received = []
    tready_signal.value = 1

    while len(received) < count:
        await RisingEdge(dut.{clk_name})
        if tvalid_signal.value == 1:
            received.append(int(tdata_signal.value))
            if tlast_signal and tlast_signal.value == 1:
                break

    return received


@cocotb.test()
async def test_{module_name}_axi_stream(dut):
    """AXI-Stream interface test"""

    # Start clock
    clock = Clock(dut.{clk_name}, {clock_period_ns}, units="ns")
    cocotb.start_soon(clock.start())

    # Reset
    dut.{rst_name}.value = {"0" if rst_active_low else "1"}
    await RisingEdge(dut.{clk_name})
    await RisingEdge(dut.{clk_name})
    dut.{rst_name}.value = {"1" if rst_active_low else "0"}
    await RisingEdge(dut.{clk_name})

    # Test data
    test_data = {test_data}

    # TODO: Adapt to actual port names
    # await axi_stream_write(dut, test_data, dut.s_axis_tdata,
    #                       dut.s_axis_tvalid, dut.s_axis_tready)

    dut._log.info("AXI-Stream test completed")
'''

        return test_code

    def generate_makefile(self, module_name: str,
                         rtl_files: List[str],
                         top_module: str,
                         simulator: str = "icarus") -> str:
        """
        Generate cocotb Makefile.

        Args:
            module_name: Module name
            rtl_files: List of RTL file paths
            top_module: Top-level module name
            simulator: Simulator (icarus/verilator/questa/vcs)

        Returns:
            Makefile content
        """
        verilog_sources = "\n".join([f"VERILOG_SOURCES += {f}" for f in rtl_files])

        makefile = f'''# Cocotb Makefile for {module_name}
# Auto-generated by VeriFlow Stage 2

# Simulator selection
SIM ?= {simulator}

# RTL source files
{verilog_sources}

# Python test module
MODULE = test_{module_name}

# Top-level module
TOPLEVEL = {top_module}

# Cocotb settings
COCOTB_HDL_TIMEUNIT = 1ns
COCOTB_HDL_TIMEPRECISION = 1ps

# Waveform dump (for Icarus)
ifeq ($(SIM),icarus)
    COMPILE_ARGS += -DVCD_OUTPUT
    SIM_ARGS += -fst
endif

# Include cocotb makefiles
include $(shell cocotb-config --makefiles)/Makefile.sim

# Clean target
clean::
\trm -rf __pycache__ sim_build results.xml *.vcd *.fst
'''

        return makefile

    def generate_integration_test(self, spec_dict: Dict[str, Any]) -> str:
        """
        Generate integration test (multi-module).

        Args:
            spec_dict: Complete MicroArchSpec dictionary

        Returns:
            Integration test code
        """
        design_name = spec_dict['design_name']
        modules = spec_dict.get('modules', [])
        data_flows = spec_dict.get('data_flow_paths', [])

        test_code = f'''"""
Integration test for {design_name}
Tests multiple modules working together
"""

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer
import random


@cocotb.test()
async def test_{design_name}_integration(dut):
    """Integration test for complete design"""

    # Start clock (assuming 156.25 MHz)
    clock = Clock(dut.clk, 6.4, units="ns")
    cocotb.start_soon(clock.start())

    # Reset
    dut.rst_n.value = 0
    await Timer(50, units="ns")
    dut.rst_n.value = 1
    await Timer(50, units="ns")

    dut._log.info("Integration test started")

    # TODO: Add specific integration test scenarios
    # Based on data flow paths:
'''

        for flow in data_flows:
            test_code += f"    # - {flow['name']}: {flow['description']}\n"

        test_code += '''

    # Run for some cycles
    for _ in range(1000):
        await RisingEdge(dut.clk)

    dut._log.info("Integration test completed")
'''

        return test_code

    def save_test(self, test_code: str, filename: str):
        """Save test code to file."""
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(test_code)
        return filepath

    def save_makefile(self, makefile_content: str, filename: str = "Makefile"):
        """Save Makefile to file."""
        filepath = self.output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(makefile_content)
        return filepath
