"""RTL Code Generator for Stage 3."""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Environment, BaseLoader

from ..stage1.spec_generator import MicroArchSpec, PipelineStage


@dataclass
class GeneratedModule:
    """Container for generated RTL module."""

    module_name: str
    verilog_code: str
    file_path: Optional[Path] = None

    # Metadata
    parameters: Dict[str, Any] = field(default_factory=dict)
    ports: List[Dict[str, Any]] = field(default_factory=list)
    internal_signals: List[str] = field(default_factory=list)

    # Quality metrics
    lines_of_code: int = 0
    comment_ratio: float = 0.0

    def __post_init__(self):
        """Calculate metrics."""
        self.lines_of_code = len(self.verilog_code.split('\n'))
        comment_lines = len([l for l in self.verilog_code.split('\n') if '//' in l])
        if self.lines_of_code > 0:
            self.comment_ratio = comment_lines / self.lines_of_code

    def save(self, output_dir: Path) -> Path:
        """Save the generated module to file."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        self.file_path = output_dir / f"{self.module_name}.v"
        self.file_path.write_text(self.verilog_code, encoding='utf-8')

        return self.file_path


# Default module template
DEFAULT_MODULE_TEMPLATE = """//////////////////////////////////////////////////////////////////////////////
// Module: {{ module_name }}
// Generated by VeriFlow-Agent 3.0
//////////////////////////////////////////////////////////////////////////////

module {{ module_name }}
{% if parameters %}
#(
{% for param in parameters %}
    parameter {{ param.name }} = {{ param.default }}{% if not loop.last %},{% endif %}
{% endfor %}
)
{% endif %}
(
{% for port in ports %}
    {{ port.direction }} {% if port.width > 1 %}[{{ port.width-1 }}:0]{% endif %} {{ port.name }}{% if not loop.last %},{% endif %}
{% endfor %}
);

//////////////////////////////////////////////////////////////////////////////
// Local Parameters
//////////////////////////////////////////////////////////////////////////////
{% for lp in localparams %}
localparam {{ lp.name }} = {{ lp.value }};
{% endfor %}

//////////////////////////////////////////////////////////////////////////////
// Internal Signals
//////////////////////////////////////////////////////////////////////////////
{% for sig in internal_signals %}
{{ sig.declaration }};
{% endfor %}

//////////////////////////////////////////////////////////////////////////////
// Implementation
//////////////////////////////////////////////////////////////////////////////

{{ implementation }}

endmodule
"""


class RTLCodeGenerator:
    """Generate RTL code from Micro-Architecture Specification."""

    def __init__(self, template_dir: Optional[Path] = None):
        self.template_dir = template_dir
        self.jinja_env = Environment(loader=BaseLoader())

        # Register custom filters
        self.jinja_env.filters['hex'] = lambda x: f"'h{x:X}"
        self.jinja_env.filters['bin'] = lambda x: f"'b{x:b}"

    def generate_from_spec(self, spec: MicroArchSpec) -> GeneratedModule:
        """Generate Verilog module from micro-architecture spec."""
        module_name = spec.module_name

        # Extract template data from spec
        template_data = self._spec_to_template_data(spec)

        # Generate code
        verilog_code = self._render_module(template_data)

        return GeneratedModule(
            module_name=module_name,
            verilog_code=verilog_code,
            parameters={p['name']: p['default'] for p in template_data.get('parameters', [])},
            ports=template_data.get('ports', []),
            internal_signals=[s['name'] for s in template_data.get('internal_signals', [])]
        )

    def _spec_to_template_data(self, spec: MicroArchSpec) -> Dict[str, Any]:
        """Convert MicroArchSpec to template data."""
        data: Dict[str, Any] = {
            'module_name': spec.module_name,
            'parameters': [],
            'ports': [],
            'localparams': [],
            'internal_signals': [],
            'implementation': ''
        }

        # Extract parameters from requirements
        if spec.requirements:
            for name, value in spec.requirements.get('parameters', {}).items():
                data['parameters'].append({
                    'name': name.upper(),
                    'default': value
                })

        # Extract ports from interfaces
        for interface in spec.interfaces:
            # Data ports
            if interface.data_width > 0:
                data['ports'].append({
                    'name': f"{interface.name}_data",
                    'direction': 'inout',
                    'width': interface.data_width
                })
            # Address ports
            if interface.addr_width > 0:
                data['ports'].append({
                    'name': f"{interface.name}_addr",
                    'direction': 'input',
                    'width': interface.addr_width
                })
            # Control ports
            if interface.protocol in ['AXI4-Lite', 'AXI4', 'Custom']:
                data['ports'].extend([
                    {'name': f"{interface.name}_valid", 'direction': 'output' if interface.direction == 'master' else 'input', 'width': 1},
                    {'name': f"{interface.name}_ready", 'direction': 'input' if interface.direction == 'master' else 'output', 'width': 1},
                ])

        # Always add clock and reset
        data['ports'].extend([
            {'name': 'clk', 'direction': 'input', 'width': 1},
            {'name': 'rst_n', 'direction': 'input', 'width': 1}
        ])

        # Generate pipeline signals if pipeline stages exist
        if spec.pipeline_stages:
            for i, stage in enumerate(spec.pipeline_stages):
                data['internal_signals'].append({
                    'name': f"stage{i}_valid",
                    'declaration': f"reg stage{i}_valid"
                })
                data['internal_signals'].append({
                    'name': f"stage{i}_data",
                    'declaration': f"reg [DATA_WIDTH-1:0] stage{i}_data"
                })

        # Generate implementation based on control/data paths
        data['implementation'] = self._generate_implementation(spec)

        return data

    def _generate_implementation(self, spec: MicroArchSpec) -> str:
        """Generate the implementation section."""
        impl_lines = []

        # Generate pipeline control logic
        if spec.pipeline_stages:
            impl_lines.append("// Pipeline control logic")
            impl_lines.append("always @(posedge clk or negedge rst_n) begin")
            impl_lines.append("    if (!rst_n) begin")

            for i in range(len(spec.pipeline_stages)):
                impl_lines.append(f"        stage{i}_valid <= 1'b0;")

            impl_lines.append("    end else begin")

            for i, stage in enumerate(spec.pipeline_stages):
                if i == 0:
                    impl_lines.append(f"        stage{i}_valid <= input_valid;")
                    impl_lines.append(f"        stage{i}_data  <= input_data;")
                else:
                    impl_lines.append(f"        stage{i}_valid <= stage{i-1}_valid;")
                    impl_lines.append(f"        stage{i}_data  <= stage{i-1}_data;")

            impl_lines.append("    end")
            impl_lines.append("end")
            impl_lines.append("")

        # Generate output assignment
        if spec.pipeline_stages:
            last_stage = len(spec.pipeline_stages) - 1
            impl_lines.append("// Output assignment")
            impl_lines.append(f"assign output_valid = stage{last_stage}_valid;")
            impl_lines.append(f"assign output_data  = stage{last_stage}_data;")
        else:
            impl_lines.append("// Pass-through implementation")
            impl_lines.append("assign output_valid = input_valid;")
            impl_lines.append("assign output_data  = input_data;")

        return '\n'.join(impl_lines)

    def _render_module(self, data: Dict[str, Any]) -> str:
        """Render the module using Jinja2 template."""
        template = self.jinja_env.from_string(DEFAULT_MODULE_TEMPLATE)
        return template.render(**data)

    def generate_fifo(self,
                      module_name: str = "sync_fifo",
                      depth: int = 16,
                      data_width: int = 32,
                      addr_width: Optional[int] = None) -> GeneratedModule:
        """Generate a synchronous FIFO module."""
        if addr_width is None:
            addr_width = (depth - 1).bit_length()

        verilog = f"""//////////////////////////////////////////////////////////////////////////////
// Module: {module_name}
// Description: Synchronous FIFO
// Depth: {depth}, Data Width: {data_width}
//////////////////////////////////////////////////////////////////////////////

module {module_name}
#(
    parameter DATA_WIDTH = {data_width},
    parameter DEPTH      = {depth},
    parameter ADDR_WIDTH = {addr_width}
)
(
    input              clk,
    input              rst_n,

    // Write interface
    input              wr_en,
    input  [DATA_WIDTH-1:0] wr_data,
    output             full,

    // Read interface
    input              rd_en,
    output [DATA_WIDTH-1:0] rd_data,
    output             empty
);

//////////////////////////////////////////////////////////////////////////////
// Internal Signals
//////////////////////////////////////////////////////////////////////////////

reg [ADDR_WIDTH-1:0] wr_ptr, rd_ptr;
reg [ADDR_WIDTH:0]   fifo_cnt;
reg [DATA_WIDTH-1:0] fifo_mem [0:DEPTH-1];

//////////////////////////////////////////////////////////////////////////////
// FIFO Control
//////////////////////////////////////////////////////////////////////////////

// Write pointer
always @(posedge clk or negedge rst_n) begin
    if (!rst_n)
        wr_ptr <= {{ADDR_WIDTH{{1'b0}}}};
    else if (wr_en && !full)
        wr_ptr <= wr_ptr + 1'b1;
end

// Read pointer
always @(posedge clk or negedge rst_n) begin
    if (!rst_n)
        rd_ptr <= {{ADDR_WIDTH{{1'b0}}}};
    else if (rd_en && !empty)
        rd_ptr <= rd_ptr + 1'b1;
end

// FIFO counter
always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        fifo_cnt <= {{ADDR_WIDTH+1{{1'b0}}}};
    end else begin
        case ({{wr_en && !full, rd_en && !empty}})
            2'b10: fifo_cnt <= fifo_cnt + 1'b1;  // Write only
            2'b01: fifo_cnt <= fifo_cnt - 1'b1;  // Read only
            default: fifo_cnt <= fifo_cnt;
        endcase
    end
end

// Memory write
always @(posedge clk) begin
    if (wr_en && !full)
        fifo_mem[wr_ptr] <= wr_data;
end

// Memory read
assign rd_data = fifo_mem[rd_ptr];

// Status
assign full  = (fifo_cnt == DEPTH);
assign empty = (fifo_cnt == 0);

endmodule
"""

        return GeneratedModule(
            module_name=module_name,
            verilog_code=verilog,
            parameters={'DATA_WIDTH': data_width, 'DEPTH': depth},
            ports=[
                {'name': 'clk', 'direction': 'input', 'width': 1},
                {'name': 'rst_n', 'direction': 'input', 'width': 1},
                {'name': 'wr_en', 'direction': 'input', 'width': 1},
                {'name': 'wr_data', 'direction': 'input', 'width': data_width},
                {'name': 'full', 'direction': 'output', 'width': 1},
                {'name': 'rd_en', 'direction': 'input', 'width': 1},
                {'name': 'rd_data', 'direction': 'output', 'width': data_width},
                {'name': 'empty', 'direction': 'output', 'width': 1},
            ]
        )

    def generate_handshake_register(self,
                                    module_name: str = "handshake_reg",
                                    data_width: int = 32) -> GeneratedModule:
        """Generate a handshake register module."""
        verilog = f"""//////////////////////////////////////////////////////////////////////////////
// Module: {module_name}
// Description: Handshake Register (valid/ready pipeline stage)
//////////////////////////////////////////////////////////////////////////////

module {module_name}
#(
    parameter DATA_WIDTH = {data_width}
)
(
    input              clk,
    input              rst_n,

    // Input interface
    input              in_valid,
    output             in_ready,
    input  [DATA_WIDTH-1:0] in_data,

    // Output interface
    output reg         out_valid,
    input              out_ready,
    output reg [DATA_WIDTH-1:0] out_data
);

//////////////////////////////////////////////////////////////////////////////
// Internal Logic
//////////////////////////////////////////////////////////////////////////////

assign in_ready = !out_valid || out_ready;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        out_valid <= 1'b0;
        out_data  <= {{DATA_WIDTH{{1'b0}}}};
    end else begin
        if (in_valid && in_ready) begin
            out_valid <= 1'b1;
            out_data  <= in_data;
        end else if (out_ready) begin
            out_valid <= 1'b0;
        end
    end
end

endmodule
"""

        return GeneratedModule(
            module_name=module_name,
            verilog_code=verilog,
            parameters={'DATA_WIDTH': data_width},
            ports=[
                {'name': 'clk', 'direction': 'input', 'width': 1},
                {'name': 'rst_n', 'direction': 'input', 'width': 1},
                {'name': 'in_valid', 'direction': 'input', 'width': 1},
                {'name': 'in_ready', 'direction': 'output', 'width': 1},
                {'name': 'in_data', 'direction': 'input', 'width': data_width},
                {'name': 'out_valid', 'direction': 'output', 'width': 1},
                {'name': 'out_ready', 'direction': 'input', 'width': 1},
                {'name': 'out_data', 'direction': 'output', 'width': data_width},
            ]
        )
