"""Yosys Interface for Stage 5."""

import os
import platform
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..common.toolchain_detect import detect_toolchain


class YosysInterface:
    """Interface to Yosys synthesis tool."""

    def __init__(self):
        # Use unified toolchain detection (handles Windows + oss-cad-suite PATH)
        self._toolchain = detect_toolchain()
        self._env = self._toolchain.shell_env()
        yosys_info = self._toolchain.tools.get("yosys")
        self.available = yosys_info.available if yosys_info else False

    @staticmethod
    def install_hint() -> str:
        """Return platform-specific Yosys installation instructions."""
        system = platform.system()
        if system == "Windows":
            return (
                "Yosys not found. Install oss-cad-suite:\n"
                "  1. Download from https://github.com/YosysHQ/oss-cad-suite-build/releases\n"
                "  2. Extract to C:\\oss-cad-suite\n"
                "  3. Add C:\\oss-cad-suite\\bin to PATH, or set YOSYSHQ_ROOT=C:\\oss-cad-suite"
            )
        elif system == "Darwin":
            return (
                "Yosys not found. Install via Homebrew:\n"
                "  brew install yosys\n"
                "Or download oss-cad-suite from https://github.com/YosysHQ/oss-cad-suite-build/releases"
            )
        else:
            return (
                "Yosys not found. Install via package manager:\n"
                "  sudo apt-get install yosys   # Debian/Ubuntu\n"
                "  sudo dnf install yosys       # Fedora\n"
                "Or download oss-cad-suite from https://github.com/YosysHQ/oss-cad-suite-build/releases"
            )

    def synthesize(
        self,
        verilog_files: List[Path],
        top_module: str,
        target: str = "generic",
        output_dir: Optional[Path] = None,
        flatten: bool = False,
    ) -> Dict[str, Any]:
        """Synthesize design using Yosys."""

        if not self.available:
            return {
                "success": False,
                "error": self.install_hint(),
            }

        if output_dir is None:
            output_dir = Path("synthesis_output")
        output_dir.mkdir(parents=True, exist_ok=True)

        # Generate Yosys script
        script_path = output_dir / "synth.ys"
        self._generate_script(script_path, verilog_files, top_module, target, output_dir, flatten=flatten)

        try:
            # Run Yosys
            result = subprocess.run(
                ["yosys", str(script_path)],
                capture_output=True,
                text=True,
                timeout=300,
                env=self._env,
            )

            # Parse output
            raw_output = result.stdout + result.stderr
            synthesis_result = self._parse_output(raw_output)
            synthesis_result["success"] = result.returncode == 0
            synthesis_result["return_code"] = result.returncode
            synthesis_result["output_dir"] = str(output_dir)
            synthesis_result["raw_output"] = raw_output

            return synthesis_result

        except subprocess.TimeoutExpired:
            return {
                "success": False,
                "error": "Synthesis timed out after 300 seconds"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }

    def _generate_script(
        self,
        script_path: Path,
        verilog_files: List[Path],
        top_module: str,
        target: str,
        output_dir: Path,
        flatten: bool = False,
    ) -> None:
        """Generate Yosys synthesis script."""

        lines = []
        lines.append("# Yosys synthesis script")
        lines.append("# Generated by VeriFlow-Agent 3.0")
        lines.append("")

        # Read input files
        for vfile in verilog_files:
            lines.append(f"read_verilog {vfile}")

        lines.append("")

        # Hierarchy
        lines.append(f"hierarchy -top {top_module}")
        lines.append("")

        # Basic synthesis
        lines.append("# Basic synthesis")
        lines.append("proc")
        lines.append("opt")
        lines.append("fsm")
        lines.append("opt")
        lines.append("memory")
        lines.append("opt")
        lines.append("")

        # Technology mapping
        if target == "generic":
            lines.append("# Generic technology mapping")
            lines.append("techmap")
            lines.append("opt")
        elif target == "ice40":
            lines.append("# iCE40 technology mapping")
            lines.append("synth_ice40")
        elif target == "ecp5":
            lines.append("# ECP5 technology mapping")
            lines.append("synth_ecp5")
        elif target == "xilinx":
            lines.append("# Xilinx technology mapping")
            lines.append("synth_xilinx")

        lines.append("")

        # Optionally flatten hierarchy before stat
        if flatten:
            lines.append("# Flatten hierarchy")
            lines.append("flatten")
            lines.append("opt")
            lines.append("")

        # Statistics
        lines.append("# Collect statistics")
        lines.append("stat")
        lines.append("")

        # Write outputs
        lines.append(f"# Write outputs")
        lines.append(f"write_json {output_dir / 'synthesis.json'}")
        lines.append(f"write_verilog {output_dir / 'synthesized.v'}")

        script_path.write_text("\n".join(lines), encoding="utf-8")

    def _parse_output(self, output: str) -> Dict[str, Any]:
        """Parse Yosys output for statistics.

        Yosys stat output format (after techmap):
            === <module> ===
               Number of wires:                 42
               Number of wire bits:            512
               Number of memories:               0
               Number of memory bits:            0
               Number of processes:              0
               Number of cells:                 85
                 $_AND_                          20
                 $_DFFE_PP_                      32
                 $_MUX_                          33
        """
        import re

        result: Dict[str, Any] = {
            "cells": {},
            "wires": 0,
            "wire_bits": 0,
            "memories": 0,
            "memory_bits": 0,
            "processes": 0,
            "cell_count_total": 0,
        }

        # Summary line pattern: "Number of <thing>:  <count>"
        summary_pattern = re.compile(r'Number of (\w[\w\s]*\w)\s*:\s*(\d+)')
        # Cell line pattern: "  $_AND_   20"  or "  $lut   5"
        cell_pattern = re.compile(r'^\s+(\$\S+)\s+(\d+)\s*$')

        in_stat_section = False

        for line in output.split('\n'):
            if '=== ' in line and ' ===' in line:
                in_stat_section = True
                continue

            if not in_stat_section:
                continue

            # Blank line after stat section ends it
            stripped = line.strip()
            if not stripped:
                continue

            # Try summary lines first
            sm = summary_pattern.search(line)
            if sm:
                key = sm.group(1).strip().lower().replace(' ', '_')
                val = int(sm.group(2))
                if key == 'wires':
                    result['wires'] = val
                elif key == 'wire_bits':
                    result['wire_bits'] = val
                elif key == 'memories':
                    result['memories'] = val
                elif key == 'memory_bits':
                    result['memory_bits'] = val
                elif key == 'processes':
                    result['processes'] = val
                elif key == 'cells':
                    result['cell_count_total'] = val
                continue

            # Try cell type lines
            cm = cell_pattern.match(line)
            if cm:
                cell_type = cm.group(1)
                count = int(cm.group(2))
                result['cells'][cell_type] = count

        return result

    def get_cell_count(self, synthesis_result: Dict[str, Any]) -> int:
        """Get total cell count from synthesis result."""
        return sum(synthesis_result.get("cells", {}).values())

    def estimate_max_frequency(self, synthesis_result: Dict[str, Any]) -> float:
        """Estimate maximum frequency based on cell types.

        Handles both pre-techmap ($lut, $dff) and post-techmap ($_AND_, $_DFFE_PP_) names.
        """
        cells = synthesis_result.get("cells", {})

        # Count LUT-like cells (pre- and post-techmap)
        lut_count = 0
        dff_count = 0
        carry_count = 0
        for name, cnt in cells.items():
            nl = name.lower()
            if 'lut' in nl or nl in ('$_and_', '$_or_', '$_xor_', '$_not_', '$_mux_',
                                      '$_nand_', '$_nor_', '$_xnor_', '$_aoi3_', '$_oai3_'):
                lut_count += cnt
            elif 'dff' in nl or 'sdff' in nl:
                dff_count += cnt
            elif 'alu' in nl or 'carry' in nl:
                carry_count += cnt

        if lut_count > 0:
            lut_delay_ns = lut_count * 0.5
            estimated_fmax_mhz = 1000.0 / lut_delay_ns
            return min(estimated_fmax_mhz, 500.0)

        return 100.0
