"""Yosys Interface for Stage 5."""

import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional


class YosysInterface:
    """Interface to Yosys synthesis tool."""

    def __init__(self):
        self.available = self._check_yosys()

    def _check_yosys(self) -> bool:
        """Check if Yosys is available."""
        try:
            result = subprocess.run(
                ["yosys", "-V"],
                capture_output=True,
                text=True,
                timeout=10
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def synthesize(
        self,
        verilog_files: List[Path],
        top_module: str,
        target: str = "generic",
        output_dir: Optional[Path] = None
    ) -> Dict[str, Any]:
        """Synthesize design using Yosys."""

        if not self.available:
            return {
                "success": False,
                "error": "Yosys not found. Please install Yosys."
            }

        if output_dir is None:
            output_dir = Path("synthesis_output")
        output_dir.mkdir(parents=True, exist_ok=True)

        # Generate Yosys script
        script_path = output_dir / "synth.ys"
        self._generate_script(script_path, verilog_files, top_module, target, output_dir)

        try:
            # Run Yosys
            result = subprocess.run(
                ["yosys", str(script_path)],
                capture_output=True,
                text=True,
                timeout=300
            )

            # Parse output
            synthesis_result = self._parse_output(result.stdout + result.stderr)
            synthesis_result["success"] = result.returncode == 0
            synthesis_result["return_code"] = result.returncode
            synthesis_result["output_dir"] = str(output_dir)

            return synthesis_result

        except subprocess.TimeoutExpired:
            return {
                "success": False,
                "error": "Synthesis timed out after 300 seconds"
            }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }

    def _generate_script(
        self,
        script_path: Path,
        verilog_files: List[Path],
        top_module: str,
        target: str,
        output_dir: Path
    ) -> None:
        """Generate Yosys synthesis script."""

        lines = []
        lines.append("# Yosys synthesis script")
        lines.append("# Generated by VeriFlow-Agent 3.0")
        lines.append("")

        # Read input files
        for vfile in verilog_files:
            lines.append(f"read_verilog {vfile}")

        lines.append("")

        # Hierarchy
        lines.append(f"hierarchy -top {top_module}")
        lines.append("")

        # Basic synthesis
        lines.append("# Basic synthesis")
        lines.append("proc")
        lines.append("opt")
        lines.append("fsm")
        lines.append("opt")
        lines.append("memory")
        lines.append("opt")
        lines.append("")

        # Technology mapping
        if target == "generic":
            lines.append("# Generic technology mapping")
            lines.append("techmap")
            lines.append("opt")
        elif target == "ice40":
            lines.append("# iCE40 technology mapping")
            lines.append("synth_ice40")
        elif target == "ecp5":
            lines.append("# ECP5 technology mapping")
            lines.append("synth_ecp5")
        elif target == "xilinx":
            lines.append("# Xilinx technology mapping")
            lines.append("synth_xilinx")

        lines.append("")

        # Statistics
        lines.append("# Collect statistics")
        lines.append("stat")
        lines.append("")

        # Write outputs
        lines.append(f"# Write outputs")
        lines.append(f"write_json {output_dir / 'synthesis.json'}")
        lines.append(f"write_verilog {output_dir / 'synthesized.v'}")

        script_path.write_text("\n".join(lines), encoding="utf-8")

    def _parse_output(self, output: str) -> Dict[str, Any]:
        """Parse Yosys output for statistics."""

        result = {
            "cells": {},
            "wires": 0,
            "wire_bits": 0,
            "processes": 0,
            "memories": 0,
            "memory_bits": 0,
        }

        # Parse statistics
        import re

        # Look for cell counts
        cell_pattern = r'(\w+)\s+(\d+)'
        in_stat_section = False

        for line in output.split('\n'):
            if '=== ' in line and ' ===' in line:
                in_stat_section = True
                continue

            if in_stat_section:
                match = re.match(cell_pattern, line.strip())
                if match:
                    cell_type = match.group(1)
                    count = int(match.group(2))
                    if cell_type in ['Number', 'Area']:
                        continue
                    result["cells"][cell_type] = count

        return result

    def get_cell_count(self, synthesis_result: Dict[str, Any]) -> int:
        """Get total cell count from synthesis result."""
        return sum(synthesis_result.get("cells", {}).values())

    def estimate_max_frequency(self, synthesis_result: Dict[str, Any]) -> float:
        """Estimate maximum frequency based on cell types."""
        # This is a rough estimation based on cell counts
        # Real timing analysis requires STA tools

        cells = synthesis_result.get("cells", {})

        # Count critical path elements
        lut_count = cells.get('$lut', 0)
        dff_count = cells.get('$dff', 0) + cells.get('$dffe', 0)
        carry_count = cells.get('$alu', 0)

        # Rough estimation: assume 500ps per LUT level, 100ps per DFF
        # This is very approximate and technology-dependent
        if lut_count > 0:
            # Estimate critical path through LUT chain
            lut_delay_ns = lut_count * 0.5
            estimated_fmax_mhz = 1000.0 / lut_delay_ns
            return min(estimated_fmax_mhz, 500.0)  # Cap at 500MHz

        return 100.0  # Default 100MHz if no logic
